#!/usr/bin/env bash

function pre_installation{
    apt-get install -y  curl ipset iproute2 haveged git  gettext gcc autoconf libtool automake make perl wget cmake asciidoc xmlto zlib1g-dev libc-ares-dev libssl-dev  libev-dev libpcre3 libpcre3-dev
    apt-get autoremove -y
}
# install pdnsd
function install_pdnsd{
    wget http://members.home.nl/p.a.rombouts/pdnsd/releases/pdnsd-1.2.9a-par.tar.gz
    tar -xvf pdnsd-1.2.9a-par.tar.gz
    cd pdnsd-1.2.9a-par
    ./configure
    make
    make install
    cd ../
}
# install chinadns
function install_chinadns{
    wget https://github.com/shadowsocks/ChinaDNS/releases/download/1.3.2/chinadns-1.3.2.tar.gz
    tar -xvf chinadns-1.3.2.tar.gz
    cd chinadns-1.3.2/
    ./configure
    make
    make install
    cd ../
}

# prepare compile environment
function install_libsodium{
    export ENV LIBSODIUM_VER=1.0.13
    wget https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VER}.tar.gz
    tar xvf libsodium-${LIBSODIUM_VER}.tar.gz
    cd libsodium-${LIBSODIUM_VER}
    ./configure --prefix=/usr
    make
    make install
    ldconfig
    cd ../
}

function install_mbedtls{
    export MBEDTLS_VER=2.6.0
    wget https://tls.mbed.org/download/mbedtls-${MBEDTLS_VER}-gpl.tgz
    tar xvf mbedtls-${MBEDTLS_VER}-gpl.tgz
    cd mbedtls-${MBEDTLS_VER}
    make SHARED=1 CFLAGS=-fPIC
    make DESTDIR=/usr install
    ldconfig
    cd ../
}

# install  shadowsocks
function install_ss{
    git clone https://github.com/shadowsocks/shadowsocks-libev.git
    cd shadowsocks-libev
    git submodule update --init --recursive
    ./autogen.sh
    ./configure
    make
    make install
    cd ../
}

# install shadowsocksR
function install_ssr{
    git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
    cd shadowsocksr-libev
    ./autogen.sh
    ./configure --prefix=/usr/local/ssr-libev
    make
    make install
    cd /usr/local/ssr-libev/bin
    mv ss-redir ssr-redir
    mv ss-local ssr-local
    ln -sf ssr-local ssr-tunnel
    mv ssr-* /usr/local/bin/
    rm -rf /usr/local/ssr-libev
    cd $1
}

# install ss-redir
function install_tproxy{
    git clone https://github.com/zfl9/ss-tproxy.git
    cd ss-tproxy
    sed -i 's/echo \"# Generated by ss-tproxy at/#echo \"# Generated by ss-tproxy at/g'  ss-tproxy
    sed -i 's/\/var\/log/\/var\/log\/tproxy/g'  ss-tproxy.conf
    cp -af ss-tproxy /usr/local/bin/
    cp -af ss-switch /usr/local/bin/
    chown root:root /usr/local/bin/ss-tproxy /usr/local/bin/ss-switch
    chmod +x /usr/local/bin/ss-tproxy /usr/local/bin/ss-switch
    mkdir -m 0755 -p /etc/tproxy
    cp -af pdnsd.conf /etc/tproxy/
    cp -af chnroute.txt /etc/tproxy/
    cp -af chnroute.ipset /etc/tproxy/
    cp -af ss-tproxy.conf /etc/tproxy/
    chown -R root:root /etc/tproxy
    chmod 0644 /etc/tproxy/*
    cd ../
}

function post_installation{
    mkdir /var/log/tproxy
    ss-tproxy flush_dnsche
    ss-tproxy update_chnip
}